version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
    expose:
      - "80"

  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./deploy/nginx/Dockerfile
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - app
